<a href="https://colab.research.google.com/github/payal1403/payal1403/blob/pythonfile/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!apt-get -y install mysql-server
!sudo service mysql status
!sudo service mysql start
!pip install mysql-connector-python
import mysql.connector

# Create a connection to the MySQL server
conn = mysql.connector.connect(user='root', password='root', unix_socket='/var/run/mysqld/mysqld.sock')

# Create a cursor to interact with the MySQL server
cursor = conn.cursor()
# Create a new database named 'library'
cursor.execute("CREATE DATABASE IF NOT EXISTS library")

# Switch to the 'library' database
cursor.execute("USE library")

# Create the 'books' table
cursor.execute('''
CREATE TABLE IF NOT EXISTS books (
    id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    author VARCHAR(255) NOT NULL,
    year_published INT
)
''')
# Connect to the MySQL server and the 'library' database
conn = mysql.connector.connect(user='root', password='root', unix_socket='/var/run/mysqld/mysqld.sock' , database='library')
cursor = conn.cursor()

books_data = [
    ("To Kill a Mockingbird", "Harper Lee", 1960),
    ("1984", "George Orwell", 1949),
    ("The Great Gatsby", "F. Scott Fitzgerald", 1925)
]

# Insert data using the cursor
cursor.executemany('''
INSERT INTO books (title, author, year_published) VALUES (%s, %s, %s)
''', books_data)

# Commit the changes
conn.commit()
cursor.execute("SELECT * FROM books")

# Fetch all the results
records = cursor.fetchall()

# Print the records
for record in records:
    print(record)

# Always remember to close the cursor and connection when done
cursor.close()
conn.close()

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  libcgi-fast-perl libcgi-pm-perl libclone-perl libencode-locale-perl libfcgi-bin libfcgi-perl
  libfcgi0ldbl libhtml-parser-perl libhtml-tagset-perl libhtml-template-perl libhttp-date-perl
  libhttp-message-perl libio-html-perl liblwp-mediatypes-perl libmecab2 libprotobuf-lite23
  liburi-perl mecab-ipadic mecab-ipadic-utf8 mecab-utils mysql-client-8.0 mysql-client-core-8.0
  mysql-server-8.0 mysql-server-core-8.0
Suggested packages:
  libdata-dump-perl libipc-sharedcache-perl libbusiness-isbn-perl libwww-perl mailx tinyca
The following NEW packages will be installed:
  libcgi-fast-perl libcgi-pm-perl libclone-perl libencode-locale-perl libfcgi-bin libfcgi-perl
  libfcgi0ldbl libhtml-parser-perl libhtml-tagset-perl libhtml-template-perl libhttp-date-perl
  libhttp-message-perl libio-html-perl liblwp-mediatypes-perl libmecab2 libprotobuf-l

In [ ]:
import mysql.connector as sql
from tabulate import tabulate
import pandas as pd

conn = mysql.connector.connect(user='root', password='root', unix_socket='/var/run/mysqld/mysqld.sock' , database='library')

cursor = conn.cursor()

cursor.execute('Select * from books')

table_rows = cursor.fetchall()

df = pd.DataFrame(table_rows)
print(tabulate(df , headers = 'keys' , tablefmt = 'psql'))




+----+-----+-----------------------+---------------------+------+
|    |   0 | 1                     | 2                   |    3 |
|----+-----+-----------------------+---------------------+------|
|  0 |   1 | To Kill a Mockingbird | Harper Lee          | 1960 |
|  1 |   2 | 1984                  | George Orwell       | 1949 |
|  2 |   3 | The Great Gatsby      | F. Scott Fitzgerald | 1925 |
|  3 |   4 | To Kill a Mockingbird | Harper Lee          | 1960 |
|  4 |   5 | 1984                  | George Orwell       | 1949 |
|  5 |   6 | The Great Gatsby      | F. Scott Fitzgerald | 1925 |
|  6 |   7 | To Kill a Mockingbird | Harper Lee          | 1960 |
|  7 |   8 | 1984                  | George Orwell       | 1949 |
|  8 |   9 | The Great Gatsby      | F. Scott Fitzgerald | 1925 |
|  9 |  10 | To Kill a Mockingbird | Harper Lee          | 1960 |
| 10 |  11 | 1984                  | George Orwell       | 1949 |
| 11 |  12 | The Great Gatsby      | F. Scott Fitzgerald | 1925 |
+----+----

In [ ]:
!mysql -u root -p -e "update library.books set year_published=NULL where title='1984'"
!mysql -u root -p -e "select * from library.books"


Enter password: 
Enter password: 
+----+-----------------------+---------------------+----------------+
| id | title                 | author              | year_published |
+----+-----------------------+---------------------+----------------+
|  1 | To Kill a Mockingbird | Harper Lee          |           1960 |
|  2 | 1984                  | George Orwell       |           NULL |
|  3 | The Great Gatsby      | F. Scott Fitzgerald |           1925 |
+----+-----------------------+---------------------+----------------+


In [ ]:
!pip install urllib3


In [ ]:
import urllib.request
request_url = urllib.request.urlopen('https://www.geeksforgeeks.org/')

print(request_url.status)

200


In [ ]:
# import requests module
import requests

# Making a get request
response = requests.get('https://api.github.com/')

# print request object
print(response.url)

# print status code
print(response.status_code)

https://api.github.com/
200


In [ ]:
import urllib.request
with urllib.request.urlopen('https://api.github.com/') as response:
   html = response.read()
   print(response.url)
   print(html)


https://api.github.com/
b'{"current_user_url":"https://api.github.com/user","current_user_authorizations_html_url":"https://github.com/settings/connections/applications{/client_id}","authorizations_url":"https://api.github.com/authorizations","code_search_url":"https://api.github.com/search/code?q={query}{&page,per_page,sort,order}","commit_search_url":"https://api.github.com/search/commits?q={query}{&page,per_page,sort,order}","emails_url":"https://api.github.com/user/emails","emojis_url":"https://api.github.com/emojis","events_url":"https://api.github.com/events","feeds_url":"https://api.github.com/feeds","followers_url":"https://api.github.com/user/followers","following_url":"https://api.github.com/user/following{/target}","gists_url":"https://api.github.com/gists{/gist_id}","hub_url":"https://api.github.com/hub","issue_search_url":"https://api.github.com/search/issues?q={query}{&page,per_page,sort,order}","issues_url":"https://api.github.com/issues","keys_url":"https://api.github.c

In [ ]:

import requests

# Making a POST request
r = requests.post('https://reqres.in/api/users/post', data ={'key':'value'})
# check status code for response received
# success code - 200
print(r)

# print content of request
print(r.json())

<Response [201]>
{'key': 'value', 'id': '817', 'createdAt': '2024-02-14T04:54:12.341Z'}


In [ ]:
import requests
import json
response = requests.get('http://reqres.in/api/users?page=2')

print('HTTP requests content:',response.content)

y=json.loads(response.content)
for i in y["data"]:
   print(i["email"])

HTTP requests content: b'{"page":2,"per_page":6,"total":12,"total_pages":2,"data":[{"id":7,"email":"michael.lawson@reqres.in","first_name":"Michael","last_name":"Lawson","avatar":"https://reqres.in/img/faces/7-image.jpg"},{"id":8,"email":"lindsay.ferguson@reqres.in","first_name":"Lindsay","last_name":"Ferguson","avatar":"https://reqres.in/img/faces/8-image.jpg"},{"id":9,"email":"tobias.funke@reqres.in","first_name":"Tobias","last_name":"Funke","avatar":"https://reqres.in/img/faces/9-image.jpg"},{"id":10,"email":"byron.fields@reqres.in","first_name":"Byron","last_name":"Fields","avatar":"https://reqres.in/img/faces/10-image.jpg"},{"id":11,"email":"george.edwards@reqres.in","first_name":"George","last_name":"Edwards","avatar":"https://reqres.in/img/faces/11-image.jpg"},{"id":12,"email":"rachel.howell@reqres.in","first_name":"Rachel","last_name":"Howell","avatar":"https://reqres.in/img/faces/12-image.jpg"}],"support":{"url":"https://reqres.in/#support-heading","text":"To keep ReqRes free,

In [ ]:
import requests
import json
response = requests.get('http://reqres.in/api/users?page=2')

print('HTTP requests content:',response.content)

y=json.loads(response.content)
print(y["data"][0]['email'])
print(y["data"][0]["id"])

HTTP requests content: b'{"page":2,"per_page":6,"total":12,"total_pages":2,"data":[{"id":7,"email":"michael.lawson@reqres.in","first_name":"Michael","last_name":"Lawson","avatar":"https://reqres.in/img/faces/7-image.jpg"},{"id":8,"email":"lindsay.ferguson@reqres.in","first_name":"Lindsay","last_name":"Ferguson","avatar":"https://reqres.in/img/faces/8-image.jpg"},{"id":9,"email":"tobias.funke@reqres.in","first_name":"Tobias","last_name":"Funke","avatar":"https://reqres.in/img/faces/9-image.jpg"},{"id":10,"email":"byron.fields@reqres.in","first_name":"Byron","last_name":"Fields","avatar":"https://reqres.in/img/faces/10-image.jpg"},{"id":11,"email":"george.edwards@reqres.in","first_name":"George","last_name":"Edwards","avatar":"https://reqres.in/img/faces/11-image.jpg"},{"id":12,"email":"rachel.howell@reqres.in","first_name":"Rachel","last_name":"Howell","avatar":"https://reqres.in/img/faces/12-image.jpg"}],"support":{"url":"https://reqres.in/#support-heading","text":"To keep ReqRes free,

In [ ]:
!pip install requests
import requests

response = requests.get('https://reqres.in/api/users?page=2')
print('HTTP Request code:' , response.status_code)
print('HTTP Request headers:',response.headers)
print('HTTP Request content:',response.content)

HTTP Request code: 200
HTTP Request headers: {'Date': 'Sat, 17 Feb 2024 03:53:26 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Report-To': '{"group":"heroku-nel","max_age":3600,"endpoints":[{"url":"https://nel.heroku.com/reports?ts=1707900134&sid=c4c9725f-1ab0-44d8-820f-430df2718e11&s=NLHmxiFHNavs9r4uzBIxEjBUTtEYxSzeN%2BZd0vyJV6A%3D"}]}', 'Reporting-Endpoints': 'heroku-nel=https://nel.heroku.com/reports?ts=1707900134&sid=c4c9725f-1ab0-44d8-820f-430df2718e11&s=NLHmxiFHNavs9r4uzBIxEjBUTtEYxSzeN%2BZd0vyJV6A%3D', 'Nel': '{"report_to":"heroku-nel","max_age":3600,"success_fraction":0.005,"failure_fraction":0.05,"response_headers":["Via"]}', 'X-Powered-By': 'Express', 'Access-Control-Allow-Origin': '*', 'Etag': 'W/"406-ut0vzoCuidvyMf8arZpMpJ6ZRDw"', 'Via': '1.1 vegur', 'Cache-Control': 'max-age=14400', 'CF-Cache-Status': 'HIT', 'Age': '427', 'Vary': 'Accept-Encoding', 'Server': 'cloudflare', 'CF-RAY': '856b1557b9f0a9c1-TP

In [ ]:
import numpy as np
import sklearn as sk
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
home = np.array([100 , 200 , 300 , 400  ])
price =np.array ([500,1000,1500,2000])

print(home)
print(price)
home_train, home_test, price_train, price_test = train_test_split(home, price, test_size=0.5, random_state=42)

print("home_train:",home_train)
print("home_test:",home_test)
print("price_train:",price_train)
print("price_test:",price_test)
model = LinearRegression()

model.fit(home_train.reshape(-1,1), price_train.reshape(-1,1))
print(model.score(home_test.reshape(-1,1),price_test.reshape(-1,1)))
print(model.predict( home_test.reshape(-1,1)))




[100 200 300 400]
[ 500 1000 1500 2000]
home_train: [100 300]
home_test: [200 400]
price_train: [ 500 1500]
price_test: [1000 2000]
1.0
[[1000.]
 [2000.]]
